services:
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mohaji
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8412:8412"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mohaji.cn4i60u0y7tm.ap-southeast-2.rds.amazonaws.com/mohaji
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - web_data:/app/logs
      - /home/ubuntu/logs/:/app/logs/
volumes:
  db_data:
  web_data:
    external: true
